#ifndef _MYENUMS_H_
#define _MYENUMS_H_

typedef enum myEnum 
{
	PERSPECTIVE,ORTHO,POSITION,AIMAT,UPDIRECTION,ASPECT,
	YANGLE, BLACK, WHITE,RED,GREEN,YELLOW,BLUE,MAGENTA,CYAN, GREY, 
	WIDTH, HEIGHT,DEPTH,AMBIENT,DIFFUSE,SPECULAR,SPOT_DIRECTION,
	DROPOFFRATE,CUTOFFANGLE,EMISSION,SHININESS,TRANSLATION,
	ROTATION,SCALE,BUFFER,SINGLE,MDOUBLE,RADIUS,STYLE,POINTSIZE,
	LINEWIDTH,FILLED,LINE,MPOINT,BACKCOLOUR,MNEAR,MFAR
};

//typedef enum BOOL {FALSE,TRUE};

typedef enum SHAPE {CUBE,SPHERE};

typedef enum TTYPE{ROAD, HILL, FIELD, RIVER};

typedef enum RES_TYPE {KEY,PISTOL,SMG} ;

#endif //_MYENUMS_H_
